### ISSUE TITLE
Type inference on generic type field access

### ISSUE THREAD

**Issue by powerboat9** [Rust-GCC/gccrs#2323] opened 2023-06-25 21:24 UTC
I tried this code:

```rust
pub struct S<T>(T);

pub fn foo<T>(x: T) {
    let y = S(x);
    y.0;
}
```

I expected to see this happen: no error

Instead, this happened:

```
test.rs:5:5: error: type annotations needed
```

### Meta

- git sha ```3ccf008b148455c4800f2a7c70be03e1dd708c59```

**Comment by philberty** [comment] 2023-06-27 09:47
I have a feeling this is going to get fixed with my work on #2330 as the issue is we are injecting too many inference variables in coercion sites at the moment.

**Comment by philberty** [comment] 2023-07-30 18:42
This is a bug in our block expression handling hmm there is another issue which has the same problem.

**Comment by philberty** [comment] 2024-11-04 14:41
no found the issue finally it was much simpler than i thought

**Closed** 2024-11-04 17:01 UTC
Labels: bug
