### ISSUE TITLE
Invalid parsing of wildcard closure parameter

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/gccrs#1910] opened 2023-02-22 07:08 UTC
I tried this code:

```rust
// { dg-additional-options "-fsyntax-only" }

pub fn encode_normal<T: RawFloat>(x: Unpacked) -> T {
    debug_assert!(
        T::MIN_SIG <= x.sig && x.sig <= T::MAX_SIG,
        "encode_normal: significand not normalized"
    );
    // Remove the hidden bit
    let sig_enc = x.sig & !(1 << T::EXPLICIT_SIG_BITS);
    // Adjust the exponent for exponent bias and mantissa shift
    let k_enc = x.k + T::MAX_EXP + T::EXPLICIT_SIG_BITS as i16;
    debug_assert!(k_enc != 0 && k_enc < T::MAX_ENCODED_EXP, "encode_normal: exponent out of range");
    // Leave sign bit at 0 ("+"), our numbers are all positive
    let bits = (k_enc as u64) << T::EXPLICIT_SIG_BITS | sig_enc;
    T::from_bits(bits.try_into().unwrap_or_else(|_| unreachable!()))
}
```

similar testcase:
```rust
fn foo() {
    let a = |_| 15;
}
```

I expected to see this happen: no error

Instead, this happened: 
```rust
../../rust/library/core/src/num/dec2flt/rawfp.rs:295:67: error: expecting ‘|’ but ‘)’ found
  295 |     T::from_bits(bits.try_into().unwrap_or_else(|_| unreachable!()))
      |                                                                   ^
../../rust/library/core/src/num/dec2flt/rawfp.rs:295:49: error: failed to parse method param in method call
  295 |     T::from_bits(bits.try_into().unwrap_or_else(|_| unreachable!()))
      |                                                 ^
../../rust/library/core/src/num/dec2flt/rawfp.rs:295:18: error: failed to parse expression in struct (or enum) expression tuple
  295 |     T::from_bits(bits.try_into().unwrap_or_else(|_| unreachable!()))
 ```

### Meta

- What version of Rust GCC were you using: 0d5fe7b9aee

**Comment by CohenArthur** [comment] 2023-02-22 07:11
Mmmmh, I'm not sure that was failing before. Investigating.

**Comment by CohenArthur** [comment] 2023-02-22 08:39
Bisecting and it seems 15ca76ea868ccb9dbb0bd1a77f9b13746220499f is the cause

**Comment by goar5670** [comment] 2023-03-02 08:24
Hello, I want to get assigned to this issue.

I think the problem is that after introducing alt patterns in 15ca76e, the second pipe token in closures are being mistaken for a start to alt pattern so my question here is, does rust allow alt patterns in closure parameters?

**Closed** 2023-03-03 16:00 UTC
Labels: bug
