### ISSUE TITLE
rust1: internal compiler error: in visit, at rust/typecheck/rust-hir-type-check-path.cc:144

### ISSUE THREAD

**Issue by bjorn3** [Rust-GCC/gccrs#1132] opened 2022-04-18 16:32 UTC
I tried this code:

```rust
mod mem {
    extern "rust-intrinsic" {
        fn transmute<U, V>(_: U) -> V;
    }
}

pub trait Hasher {
    fn write(&mut self, bytes: &[u8]);
    fn write_u16(&mut self, i: u16) {
        self.write(&mem::transmute::<_, [u8; 2]>(i))
    }
}

pub struct SipHasher;

impl Hasher for SipHasher {
    #[inline]
    fn write(&mut self, msg: &[u8]) {}
}
```

I expected to see this happen: *explanation*

Instead, this happened:

```
rust1: internal compiler error: in visit, at rust/typecheck/rust-hir-type-check-path.cc:144
0x204e319 internal_error(char const*, ...)
	???:0
0x8027ef fancy_abort(char const*, int, char const*)
	???:0
0xa10a9e Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::PathInExpression&)
	???:0
0x9c137c Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
	???:0
0x9c2364 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::CallExpr&)
	???:0
0x9c137c Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
	???:0
0x9c4fca Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BorrowExpr&)
	???:0
0x9c137c Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
	???:0
0x9d5a10 Rust::TyTy::TypeCheckMethodCallExpr::visit(Rust::TyTy::FnType&)
	???:0
0x9cd012 Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::MethodCallExpr&)
	???:0
0x9c137c Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
	???:0
0x9b7b6a Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)
	???:0
0x9c137c Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
	???:0
0x9be73b Rust::Resolver::TraitResolver::go(Rust::HIR::TypePath&)
	???:0
0x9cd567 Rust::Resolver::TypeCheckItem::visit(Rust::HIR::ImplBlock&)
	???:0
0x9b8d92 Rust::Resolver::TypeResolution::Resolve(Rust::HIR::Crate&)
	???:0
0x8c88a8 Rust::Session::parse_file(char const*)
	???:0
0x8c9548 Rust::Session::parse_files(int, char const**)
	???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
Compiler returned: 1
```

or as variation:

```rust
mod mem {
    extern "rust-intrinsic" {
        fn transmute<U, V>(_: U) -> V;
    }
}

pub trait Hasher {
    fn write(&mut self, bytes: &[u8]);
    fn write_u16(&mut self, i: u16) {
        self.write(&mem::transmute::<_, [u8; 2]>(i))
    }
}
```

```
rust1: internal compiler error: in visit_generic_predicates, at rust/privacy/rust-reachability.cc:56
0x204e319 internal_error(char const*, ...)
	???:0
0x8027ef fancy_abort(char const*, int, char const*)
	???:0
0x9ceb45 Rust::Privacy::Resolver::resolve(Rust::HIR::Crate&)
	???:0
0x8c8927 Rust::Session::parse_file(char const*)
	???:0
0x8c9548 Rust::Session::parse_files(int, char const**)
	???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
Compiler returned: 1
```

### Meta

- What version of Rust GCC were you using, git sha if possible.

**Comment by liushuyu** [comment] 2022-04-20 03:18
Reduced case:

```rust
pub trait Hasher {}
```

Backtrace with debug info:

```
rust1: internal compiler error: in visit_generic_predicates, at rust/privacy/rust-reachability.cc:56
0x74686b Rust::Privacy::ReachabilityVisitor::visit_generic_predicates(std::vector<std::unique_ptr<Rust::HIR::GenericParam, std::default_delete<Rust::HIR::GenericParam> >, std::allocator<std::unique_ptr<Rust::HIR::GenericParam, std::default_delete<Rust::HIR::GenericParam> > > > const&, Rust::Privacy::ReachLevel)
        ../../gcc/rust/privacy/rust-reachability.cc:56
0xb10d68 Rust::Privacy::Resolver::resolve(Rust::HIR::Crate&)
        ../../gcc/rust/privacy/rust-privacy-check.cc:41
0x9ec2ce Rust::Session::parse_file(char const*)
        ../../gcc/rust/rust-session-manager.cc:704
0x9ec94a Rust::Session::parse_files(int, char const**)
        ../../gcc/rust/rust-session-manager.cc:579
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
```

**Comment by CohenArthur** [comment] 2022-04-20 07:31
> Reduced case:
> 
> <snip>
>
> Probably addressable by #1135

Yeah, this part of the issue is the same as #1135 so the "initial draft fix" should fix it. However, there is also an ICE in the typechecking pass which I think is separate

**Comment by liushuyu** [comment] 2022-04-20 09:00
> > Reduced case:
> > 
> > Probably addressable by #1135
> 
> Yeah, this part of the issue is the same as #1135 so the "initial draft fix" should fix it. However, there is also an ICE in the typechecking pass which I think is separate

Yes. I have conducted a preliminary investigation, and it seems like this was due to `transmute` not being implemented as an intrinsic. 

Related: #658.

**Comment by philberty** [comment] 2022-04-21 18:03
Updated stack trace:

```
rust1: internal compiler error: in visit, at rust/typecheck/rust-hir-type-check-path.cc:144
0x1302d7a Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::PathInExpression&)
        ../../gccrs/gcc/rust/typecheck/rust-hir-type-check-path.cc:144
0x119b5b1 Rust::HIR::PathInExpression::accept_vis(Rust::HIR::HIRFullVisitor&)
        ../../gccrs/gcc/rust/hir/tree/rust-hir-full-test.cc:3785
0x127ad67 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
        ../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.h:49
0x119bf15 Rust::HIR::CallExpr::accept_vis(Rust::HIR::HIRFullVisitor&)
        ../../gccrs/gcc/rust/hir/tree/rust-hir-full-test.cc:4041
0x127ad67 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
        ../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.h:49
0x119b82b Rust::HIR::BorrowExpr::accept_vis(Rust::HIR::HIRFullVisitor&)
        ../../gccrs/gcc/rust/hir/tree/rust-hir-full-test.cc:3849
0x127ad67 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
        ../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.h:49
0x12b2be4 Rust::TyTy::TypeCheckMethodCallExpr::visit(Rust::TyTy::FnType&)
        ../../gccrs/gcc/rust/typecheck/rust-tyty.cc:3073
0x12aa55f Rust::TyTy::FnType::accept_vis(Rust::TyTy::TyVisitor&)
        ../../gccrs/gcc/rust/typecheck/rust-tyty.cc:1133
0x1279a5a Rust::TyTy::TypeCheckMethodCallExpr::go(Rust::TyTy::BaseType*, Rust::HIR::MethodCallExpr&, Rust::TyTy::BaseType*, Rust::Resolver::TypeCheckContext*)
        ../../gccrs/gcc/rust/typecheck/rust-tyty-call.h:96
0x119bf4d Rust::HIR::MethodCallExpr::accept_vis(Rust::HIR::HIRFullVisitor&)
        ../../gccrs/gcc/rust/hir/tree/rust-hir-full-test.cc:4047
0x127ad67 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
        ../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.h:49
0x1272aab Rust::Resolver::TypeCheckExpr::visit(Rust::HIR::BlockExpr&)
        ../../gccrs/gcc/rust/typecheck/rust-hir-type-check.cc:130
0x119bff5 Rust::HIR::BlockExpr::accept_vis(Rust::HIR::HIRFullVisitor&)
        ../../gccrs/gcc/rust/hir/tree/rust-hir-full-test.cc:4065
0x127ad67 Rust::Resolver::TypeCheckExpr::Resolve(Rust::HIR::Expr*, bool)
        ../../gccrs/gcc/rust/typecheck/rust-hir-type-check-expr.h:49
0x12e18df Rust::Resolver::TraitItemReference::resolve_item(Rust::HIR::TraitItemFunc&)
        ../../gccrs/gcc/rust/typecheck/rust-hir-trait-resolve.cc:122
0x12e1678 Rust::Resolver::TraitItemReference::on_resolved()
        ../../gccrs/gcc/rust/typecheck/rust-hir-trait-resolve.cc:80
0x12775e3 Rust::Resolver::TraitReference::on_resolved()
        ../../gccrs/gcc/rust/typecheck/rust-hir-trait-ref.h:368
0x1279f5b Rust::Resolver::TraitResolver::Resolve(Rust::HIR::TypePath&)
        ../../gccrs/gcc/rust/typecheck/rust-hir-trait-resolve.h:73
0x119cbdb Rust::HIR::ImplBlock::accept_vis(Rust::HIR::HIRFullVisitor&)
        ../../gccrs/gcc/rust/hir/tree/rust-hir-full-test.cc:4389

```

The assertion here is part of a silly nullptr bug in the resolving of the segments i have been meaning to fix since last year lol

**Comment by philberty** [comment] 2022-04-28 12:52
This was fixed between these two PRs:

https://github.com/Rust-GCC/gccrs/pull/1184
https://github.com/Rust-GCC/gccrs/pull/1190

**Comment by philberty** [comment] 2022-04-28 12:53
Actually i will repoen to lets bors close out from #1190

**Closed** 2022-04-28 14:46 UTC
Labels: bug
